resource_group: myResourceGroup
location: southeastasia
vnet_name: myVnet
subnet_name: mySubnet
pip_name: myPublicIP
nsg_name: myNSG
nic_name: myNIC
vm_name: myVM01
vm_size: Standard_B1s
admin_username: azureuser
